#!/usr/bin/php
<?php

declare(strict_types=1);

use Tischmann\Atlantis\{Console};

require_once __DIR__ . "/bootstrap/require.php";

require_once __DIR__ . "/bootstrap/config.php";

require_once __DIR__ . "/vendor/autoload.php";

$migrations = [
    new App\Database\Users()
];

foreach (Console::parse($argv) as $command => $value) {
    switch ($command) {
        case 'remove':
            Console::print(
                message: "Очистка БД",
                postfix: "",
                separate: true
            );

            foreach ($migrations as $migration) {
                if (!$migration->drop()) {
                    Console::print(
                        message: "Ошибка при удалении таблицы",
                        postfix: $migration::name()
                    );
                } else {
                    Console::print(
                        message: "Таблица удалена",
                        postfix: $migration::name()
                    );
                }
            }

            Console::print(
                message: "Очистка БД завершена",
                postfix: "",
                separate: true
            );
            break;
        case 'create':
            Console::print(
                message: "Создание БД",
                postfix: "",
                separate: true
            );

            foreach ($migrations as $migration) {
                if (!$migration->create()) {
                    Console::print(
                        message: "Ошибка при создании таблицы",
                        postfix: $migration::name()
                    );
                } else {
                    Console::print(
                        message: "Таблица создана",
                        postfix: $migration::name()
                    );
                }
            }

            Console::print(
                message: "Создание БД завершено",
                postfix: "",
                separate: true
            );
            break;
        case 'seed':
            Console::print(
                message: "Заполнение БД завершено",
                postfix: "",
                separate: true
            );

            foreach ($migrations as $migration) {
                $inserted = $migration->seed();

                Console::print(
                    message: "Записей добавлено: {$inserted}",
                    postfix: $migration::name()
                );
            }

            Console::print(
                message: "Заполнение БД завершено",
                postfix: "",
                separate: true
            );
            break;
    }
}
